### ISSUE TITLE
Feature request: Import .cvt file compiled by CC65

### ISSUE THREAD

**Issue by xahmol** [M3wP/GEOSBuild#1]
Hi, recently encountered your GEOSBuild tool, as I was searching for a way to automate building a GEOS disk image from my compiled GEOS application.

I have tried c1541 from VICE, but the -geoswrite option does not yet work for me making a working disk from the .cvt file created by the CC65 linker tool (cl65).

So I was eager to try your tool, but see your tool does not use a .cvt tool as input, but separate header and binary files.

As I presently use the CC65 GEOS Resource Compiler (grc65) to create the header file as part of the .cvt file, I did not find a way to output the header file seperately in a usable form from GRC65 as it injects variables that are compiled together with the binaries part of the compiled .cvt
(Hope this in any way makes sense to you).

So:
- would you consider having a .cvt file as input as a feature request?
- did I overlook something and is using your tool together with using GRC65 actually possible?
- any other tips?

Details of my environment:
- coding in C using GEOSLib for CC65
- desired output image a GEOS D81 disk image
- using it with GEOS128 v2 on a Commodore 128 DCR.

Thanks!

Regards,
Xander Mol

**Comment by M3wP** [comment]
Hello,

I'm surprised that c1541 didn't work for you.  Perhaps the disk needs to be a GEOS disk before it will allow you do use geosread/geoswrite?  I don't have any .cvt files to test this with.  If you use my other tool, D64Explorer, you can create a blank GEOS disk image and try c1541 with it?

If this still doesn't work, I might be able to add the feature but it will take some time.  The project (and all the debugging files) is in my archives...  There is also not a great deal of information available (it seems to have recently gone offline) about .cvt files but I have found a reference I can use.

Get back to me about your retry of c1541 and I'll see what I can do.


Daniel.

________________________________
From: Xander Mol ***@***.***>
Sent: 06 January 2023 03:42
To: M3wP/GEOSBuild ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [M3wP/GEOSBuild] Feature request: Import .cvt file compiled by CC65 (Issue #1)


Hi, recently encountered your GEOSBuild tool, as I was searching for a way to automate building a GEOS disk image from my compiled GEOS application.

I have tried c1541 from VICE, but the -geoswrite option does not yet work for me making a working disk from the .cvt file created by the CC65 linker tool (cl65).

So I was eager to try your tool, but see your tool does not use a .cvt tool as input, but separate header and binary files.

As I presently use the CC65 GEOS Resource Compiler (grc65) to create the header file as part of the .cvt file, I did not find a way to output the header file seperately in a usable form from GRC65 as it injects variables that are compiled together with the binaries part of the compiled .cvt
(Hope this in any way makes sense to you).

So:

  *   would you consider having a .cvt file as input as a feature request?
  *   did I overlook something and is using your tool together with using GRC65 actually possible?
  *   any other tips?

Details of my environment:

  *   coding in C using GEOSLib for CC65
  *   desired output image a GEOS D81 disk image
  *   using it with GEOS128 v2 on a Commodore 128 DCR.

Thanks!

Regards,
Xander Mol

**Comment by xahmol** [comment]
Nope, alas using a GEOS disk as inout does not help.

Did look some further in what goes wrong, and I see that for me c1541
-geoswrite only writes the file header part of the .CVT, not the rest.

See
![image](https://user-images.githubusercontent.com/53264603/211204416-18f0cdc5-3dcc-4729-907d-b4235ed478ee.png)

Left in screenshot is the c1541 created file. On a GEOS empty disk created
with your D64Explorer.  On Hex view you see only the GEOS file header has
been written.
Right is dropping the .CVT file into DirMaster on a GEOS disk. Hex view
shows now everything, not only the file header.

Frustrating.

And thanks for thinking along.

Xander Mol



Op za 7 jan. 2023 om 07:44 schreef M3wP ***@***.***>:

**Comment by xahmol** [comment]
Did some more checking: c1541 -geoswrite works fine with .CVT files I throw
at it not created by projects using the GRC65 tool of CC65 to create a file
header. Think it might be caused by GRC65 outputting a file block size in
the directory entry code I see of 0. Also shows if you watch the disk
images as in the screenshot above outside GEOS: size shows indeed as 0.
Seems that while DirMaster apparently can handle that, c1541 can not.

But in that case the issue is within the CC65 GEOS implementation, And
indeed see the same happening with other projects written in C for GEOS
using GRC65.
So guess I need to contact the creator of either GRC65 or the GEOSlb in
CC65.

Thanks again, and if you have any tips please let me know.

Xander

Op zo 8 jan. 2023 om 15:14 schreef Xander Mol ***@***.***>:

**Comment by xahmol** [comment]
OK. If I can not get CC65 to create a working .CVT to convert by c1541, then I hack it to create bin files that are suited for your GEOSBuild tool....
Happy to say that I now have changed my buildworkflow to create a header and application BIN file that succesfully compile with GEOSBuild to a working GEOS disk image.

Happy! And many thanks for your tool. 

Issue can be closed.

**Comment by M3wP** [comment]
Oh that's great news.  I'm glad it has worked out successfully for you!


________________________________
